export const SEARCH_SCRAPER_REQUEST = 'SEARCH_SCRAPER_REQUEST'
export const SEARCH_SCRAPER_SUCCESS = 'SEARCH_SCRAPER_SUCCESS'
export const SEARCH_SCRAPER_FAIL = 'SEARCH_SCRAPER_FAIL'

export const TRACKED_PRODUCTS_REQUEST = 'TRACKED_PRODUCTS_REQUEST'
export const TRACKED_PRODUCTS_SUCCESS = 'TRACKED_PRODUCTS_SUCCESS'
export const TRACKED_PRODUCTS_FAIL = 'TRACKED_PRODUCTS_FAIL'